services:
  - type: web
    name: sparkler-ai
    env: python
    branch: master
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:10000 app:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.3
